name: "coverage"

on:
  push:
    branches:
      - master

env:
  extensions: "json, xdebug"
  cache-version: "1"
  composer-version: "v2"
  composer-install: "composer install --no-interaction --no-progress --prefer-dist"
  coverage: "xdebug"

jobs:
  coverage:
    name: "Coverage"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PHP cache environment"
        id: "extcache"
        uses: "shivammathur/cache-extensions@v1"
        with:
          php-version: "8.5"
          extensions: "${{ env.extensions }}"
          key: "${{ env.cache-version }}"

      - name: "Cache PHP extensions"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.extcache.outputs.dir }}"
          key: "${{ steps.extcache.outputs.key }}"
          restore-keys: "${{ steps.extcache.outputs.key }}"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.5"
          extensions: "${{ env.extensions }}"
          tools: "composer:${{ env.composer-version }}"
          coverage: "${{ env.coverage }}"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get Composer cache directory"
        id: "composercache"
        run: 'echo "::set-output name=dir::$(composer config cache-files-dir)"'

      - name: "Cache PHP dependencies"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composercache.outputs.dir }}"
          key: "${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "${{ runner.os }}-composer-"

      - name: "Install dependencies"
        run: "${{ env.composer-install }}"

      - name: "Env variables"
        run: |
          echo "API_MERCHANT=${{ secrets.API_MERCHANT }}" >> .env
          echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env
          echo "API_URL_REST=${{ secrets.API_URL_REST }}" >> .env
          echo "APPLICATION_ENV='sdk-github'" >> .env
          echo "CF_ACCESS_CLIENT_ID=${{ secrets.CF_ACCESS_CLIENT_ID }}" >> .env
          echo "CF_ACCESS_CLIENT_SECRET=${{ secrets.CF_ACCESS_CLIENT_SECRET }}" >> .env

      - name: "Build Codeception actors"
        run: "vendor/bin/codecept build -v"

      - name: "Regenerate autoloader"
        run: "composer dump-autoload --optimize"

      - name: "Run tests with coverage"
        env:
          XDEBUG_MODE: coverage
        run: |
          vendor/bin/codecept run --coverage --coverage-xml coverage.xml

      - name: "Upload coverage to Coveralls"
        uses: coverallsapp/github-action@v2
        with:
          file: tests/_output/coverage.xml
          format: clover
